knife4j:
  production: false
  enable: true
  basic:
    enable: false
    username: renren
    password: 2ZABCDEUgF
  setting:
    enableFooter: false
spring:
  datasource:
    druid:
      #MySQL
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-j6ca3vf35i70jyufpzo.mysql.rds.aliyuncs.com/xiaozhi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      username: smawatch_test
      password: smawatch@2022
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 6000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: false
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  data:
    redis:
      host: 47.115.60.222         # Redis服务器地址
      port: 32772              # Redis服务器连接端口
      password:              # Redis服务器连接密码（默认为空）
      database: 0            # Redis数据库索引（默认为0）
      timeout: 10000ms       # 连接超时时间（毫秒）
      lettuce:
        pool:
          max-active: 8      # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 8        # 连接池中的最大空闲连接
          min-idle: 0        # 连接池中的最小空闲连接
        shutdown-timeout: 100ms  # 客户端优雅关闭的等待时间

feign:
  client:
    config:
      iotSolutionClient:
        # 这是 Feign 的配置块，主要用于设置超时、日志级别等
        loggerLevel: full

iot:
  solution:
    url: https://api.iot-solution.net/kotlinweb

sma:
  token: uyZ7UQVkO2fGnF7JE14dyIH6fNJ0Hiho4xLdsCHliRrYVpBK5hai5TWVeSVj
  agentId: 59f343e9a88c42b19af9783bec7272a6