services:
  # Python主服务
  xz-server:
    image: ghcr.nju.edu.cn/xinnan-tech/xiaozhi-esp32-server:server_latest
    container_name: xz-server
    restart: always
    ports:
      - "8000:8000"
      - "8003:8003"
    volumes:
      - "/home/work/sma_xz/xz-server:/opt/xiaozhi-esp32-server"
    environment:
      - TZ=Asia/Shanghai
    command: python app.py
    depends_on:
      - xz-redis
      - xz-web
    networks:
      - sma-net
  # Redis服务
  xz-redis:
    image: redis:latest
    container_name: xz-redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    command: redis-server --requirepass admin@123
    networks:
      - sma-net

  # Java Web服务
  xz-web:
    image: eclipse-temurin:21-jre
    container_name: xz-web
    restart: always
    ports:
      - "8002:8002"
    volumes:
      - "/home/work/sma_xz/xz-web:/home/work/sma_xz/xz-web"
    environment:
      - TZ=Asia/Shanghai
      - SPRING_DATA_REDIS_HOST=xz-redis
      - SPRING_DATA_REDIS_PASSWORD=admin@123
      - SPRING_DATA_REDIS_PORT=6379
    command: >
      sh -c "java -jar /home/work/sma_xz/xz-web/server/xiaozhi-esp32-api.jar"
    depends_on:
      - xz-redis
    networks:
      - sma-net

  # Nginx 代理服务
  xz-nginx:
    image: nginx:alpine
    container_name: xz-nginx
    restart: always
    ports:
      - "80:80"          # HTTP 访问端口
      - "443:443"      # 如需 HTTPS 可启用
    volumes:
      - /home/work/sma_xz/xz-web/web:/home/work/sma_xz/xz-web/web
      - ./xz-nginx/cert:/home/work/sma_xz/xz-nginx/cert
      - ./xz-nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./xz-nginx/logs:/var/log/nginx
    depends_on:
      - xz-web
    networks:
      - sma-net


networks:
  sma-net:
    name: sma-net
    driver: bridge
