events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;
    error_log  /var/log/nginx/error.log warn;

    server {
        listen 80;
        #填写证书绑定的域名
        server_name ai-c.iot-solution.net;
        #将所有HTTP请求通过rewrite指令重定向到HTTPS.
        rewrite ^(.*)$ https://$host$1;
        location / {
          index index.html index.htm;
        }
    }

    server {
         listen 443 ssl;
         server_name ai-c.iot-solution.net;

         ssl_certificate /home/work/sma_xz/xz-nginx/cert/iot-solution.net.pem;
         ssl_certificate_key /home/work/sma_xz/xz-nginx/cert/iot-solution.net.key;

          # 转发到编译后到web目录
        location / {
			root /home/work/sma_xz/xz-web/web/dist;
			try_files $uri $uri/ /index.html;
		}

         location /xiaozhi/ {
            proxy_pass http://xz-web:8002;
            proxy_set_header Host $host;
            proxy_cookie_path /xiaozhi/ /;

            # 核心IP转发配置
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # WebSocket支持（保持原有配置）
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            # 其他头信息（可选）
            proxy_set_header Referer $http_referer;
            proxy_set_header Cookie $http_cookie;
        }
    }
}